whatever-x/backend

build.gradle, src/main/kotlin/com/whatever/config/SecurityConfig.kt, src/main/kotlin/com/whatever/domain/auth/client/dto/KakaoUserInfoDto.kt, src/main/kotlin/com/whatever/domain/auth/controller/AuthController.kt, src/main/kotlin/com/whatever/domain/auth/exception/AuthException.kt, src/main/kotlin/com/whatever/domain/auth/exception/AuthExceptionCode.kt, src/main/kotlin/com/whatever/domain/auth/service/AuthService.kt, src/main/kotlin/com/whatever/domain/auth/service/JwtHelper.kt, src/main/kotlin/com/whatever/domain/auth/service/provider/AppleUserProvider.kt, src/main/kotlin/com/whatever/domain/auth/service/provider/KakaoUserProvider.kt, src/main/kotlin/com/whatever/domain/auth/service/provider/SocialUserProvider.kt, src/main/kotlin/com/whatever/domain/user/model/User.kt, src/main/kotlin/com/whatever/domain/user/repository/UserRepository.kt, src/main/kotlin/com/whatever/global/exception/GlobalControllerAdvice.kt, src/main/kotlin/com/whatever/global/jwt/JwtProvider.kt, src/main/kotlin/com/whatever/global/jwt/exception/JwtException.kt, src/main/kotlin/com/whatever/global/jwt/exception/JwtExceptionCode.kt, src/main/kotlin/com/whatever/global/security/exception/SecurityException.kt, src/main/kotlin/com/whatever/global/security/exception/SecurityExceptionCode.kt, src/main/kotlin/com/whatever/global/security/filter/JwtAuthenticationFilter.kt, src/main/kotlin/com/whatever/global/security/filter/JwtExceptionFilter.kt, src/main/kotlin/com/whatever/global/security/handler/CaramelAccessDeniedHandler.kt, src/main/kotlin/com/whatever/global/security/handler/CaramelAuthenticationEntryPoint.kt, src/main/kotlin/com/whatever/global/security/principal/CaramelUserDetails.kt, src/main/kotlin/com/whatever/global/security/util/HttpServletResponseUtil.kt, src/main/kotlin/com/whatever/global/security/util/SecurityUtil.kt, src/main/resources/application-test.yaml, src/test/kotlin/com/whatever/domain/auth/service/provider/KakaoUserProviderTest.kt
- #21 
- SpringSecurity 추가
- Jwt 인증 필터 추가
- 로그인 추가 & 회원가입 로직과 병합
- 플랫폼별로 회원가입에 대한 로직을 전략패턴으로 분리하려고 해봤습니다
=> [Feat] 카카오 로그인 추가

build.gradle, src/main/kotlin/com/whatever/domain/auth/service/AuthService.kt, src/main/kotlin/com/whatever/util/RedisUtil.kt, src/test/kotlin/com/whatever/util/RedisUtilTest.kt
- close #23 
- refreshToken 저장, 조회, 삭제 로직이 있는 RedisUtil 추가
- AuthService.createTokenAndSave()의 refreshToken 저장 코드 변경
- 생각해보니 저희가 멀티플랫폼이어서 한 유저에 다수의 refresh token이 저장되어야 할것 같았습니다.
- 따라서 로그인/회원가입 요청이나, 토큰 재발급 요청 시 client의 device 종류(혹은 device 고유의 id)도 함께 수신해야 할것 같습니다.
- 코드에는 deviceId를 반영해두었고 임시 문자열로 채워두었습니다.
=> [Feat] RedisUtil 추가

src/main/kotlin/com/whatever/config/properties/OauthProperties.kt, src/main/kotlin/com/whatever/domain/auth/client/AppleFeignClient.kt, src/main/kotlin/com/whatever/domain/auth/client/KakaoFeignClient.kt, src/main/kotlin/com/whatever/domain/auth/client/dto/AppleIdTokenDto.kt, src/main/kotlin/com/whatever/domain/auth/client/dto/OIDCPublicKeysDto.kt, src/main/kotlin/com/whatever/domain/auth/controller/AuthController.kt, src/main/kotlin/com/whatever/domain/auth/dto/AppleAuthFormData.kt, src/main/kotlin/com/whatever/domain/auth/dto/SignupSigninRequest.kt, src/main/kotlin/com/whatever/domain/auth/service/OIDCHelper.kt, src/main/kotlin/com/whatever/domain/auth/service/provider/AppleUserProvider.kt, src/main/resources/application.yaml
- close #29 
- Apple OIDC 를 통한 UserProvider 구현
- 기존 코드에는 accessToken을 사용한 로그인/회원가입만 존재합니다. 추후 id token을 사용하여 로그인 가능하도록 수정해야합니다.
- AuthController의 기본 endpoint 경로에 "/v1"을 추가했습니다. 앞으로 도메인별로 endpoint를 추가할 때 이와 같이 반영해주세요~
- 기존 AuthController.signUp() 메서드에 @RequestBody가 없어 동작하지 않아 수정했습니다.
=> [Feat] Apple OIDC 추가

src/main/kotlin/com/whatever/domain/auth/client/dto/KakaoIdTokenDto.kt, src/main/kotlin/com/whatever/domain/auth/controller/AuthController.kt, src/main/kotlin/com/whatever/domain/auth/service/AuthService.kt, src/main/kotlin/com/whatever/domain/auth/service/provider/AppleUserProvider.kt, src/main/kotlin/com/whatever/domain/auth/service/provider/KakaoUserProvider.kt, src/main/kotlin/com/whatever/domain/auth/service/provider/SocialUserProvider.kt, src/main/kotlin/com/whatever/global/exception/GlobalControllerAdvice.kt
- #41 
- KakaoLogin accesstoken -> idToken 사용하도록 변경
- @given-dragon 만들어놓은 applelogin component 조합하여 애플로그인 IdToken으로 동작하도록 수정
=> [Feat] KakaoLogin, AppleLogin OIDC 방식으로 동작하도록 수정

src/main/kotlin/com/whatever/domain/auth/service/OIDCHelper.kt
- close #54 
- Jws<Claims>.toAppleIdTokenPayload() 변경
=> [Fix] null, Boolean, String 등 다양한 타입에 대해 파싱할 수 있도록 변경

src/main/kotlin/com/whatever/domain/content/controller/ContentController.kt, src/main/kotlin/com/whatever/domain/content/controller/dto/request/CreateContentRequest.kt, src/main/kotlin/com/whatever/domain/content/exception/ContentException.kt, src/main/kotlin/com/whatever/domain/content/exception/ContentExceptionCode.kt, src/main/kotlin/com/whatever/domain/content/model/ContentDetail.kt, src/main/kotlin/com/whatever/domain/content/service/ContentService.kt, src/main/kotlin/com/whatever/domain/content/service/MemoCreator.kt, src/main/kotlin/com/whatever/domain/content/tag/repository/TagRepository.kt, src/test/kotlin/com/whatever/domain/ControllerTestSupport.kt, src/test/kotlin/com/whatever/domain/content/controller/ContentControllerTest.kt
- #53 
- MemoCreator#createMemo 로직에서, content table에 저장하고 mapping table에 저장하는 부분 한번 봐주세요
- 로컬에서 작업 환경 편하게 할 수 있는 방법이 없을까요? 현재는 매번 header에 accessToken을 얻어서 넣어주고 있어요
- POST 후 테이블 데이터를 보고싶은데, GET을 구현하는것 말고 따로 테이블을 볼 수 있는 방법이 있을까요?
=> [Feat] 컨텐츠 생성 - 메모

src/main/kotlin/com/whatever/domain/auth/service/AuthService.kt, src/main/kotlin/com/whatever/domain/calendarevent/eventrecurrence/model/ScheduleRecurrenceOverride.kt, src/main/kotlin/com/whatever/domain/calendarevent/eventrecurrence/model/TaskRecurrenceOverride.kt, src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/model/ScheduleEvent.kt, src/main/kotlin/com/whatever/domain/calendarevent/taskevent/model/TaskEvent.kt, src/main/kotlin/com/whatever/domain/content/model/Content.kt, src/main/kotlin/com/whatever/domain/content/service/ContentService.kt, src/main/kotlin/com/whatever/domain/content/tag/model/Tag.kt, src/main/kotlin/com/whatever/domain/content/tag/model/TagContentMapping.kt, src/main/kotlin/com/whatever/domain/couple/model/Couple.kt, src/main/kotlin/com/whatever/domain/couple/service/CoupleService.kt, src/main/kotlin/com/whatever/domain/sample/model/SampleEntity.kt, src/main/kotlin/com/whatever/domain/sample/service/SampleService.kt, src/main/kotlin/com/whatever/domain/user/model/User.kt, src/main/kotlin/com/whatever/global/security/filter/JwtAuthenticationFilter.kt
- spring data jpa에서, entity @id에 Long  = 0L이어도 new라고 간주하여 새로운 id를 만들게 된다.
- null임이 자명함에도 불구하고 null safety한 코틀린에서 !!를 사용함에 있어 불편함이 많아 변경
=> [Refactor] entity id nullable -> null safety 0L로 수정

.gitignore, src/main/kotlin/com/whatever/domain/user/dto/PostUserProfileRequest.kt, src/main/kotlin/com/whatever/domain/user/model/User.kt, src/main/resources/initial-data-local.sql, src/test/kotlin/com/whatever/domain/auth/service/provider/KakaoUserProviderTest.kt, src/test/kotlin/com/whatever/domain/user/controller/UserControllerTest.kt
- close #78 
- 기존 3-10자를 디자인 기준인 2-8자로 변경
=> [Fix] user nickname 길이 제약조건 변경

src/main/kotlin/com/whatever/domain/couple/controller/CoupleController.kt, src/main/kotlin/com/whatever/domain/couple/controller/dto/response/CoupleInfoResponse.kt, src/main/kotlin/com/whatever/domain/couple/exception/CoupleAccessDeniedException.kt, src/main/kotlin/com/whatever/domain/couple/exception/CoupleException.kt, src/main/kotlin/com/whatever/domain/couple/exception/CoupleExceptionCode.kt, src/main/kotlin/com/whatever/domain/couple/exception/CoupleIllegalStateException.kt, src/main/kotlin/com/whatever/domain/couple/model/Couple.kt, src/main/kotlin/com/whatever/domain/couple/model/CoupleStatus.kt, src/main/kotlin/com/whatever/domain/couple/service/CoupleService.kt, src/main/kotlin/com/whatever/global/constants/CaramelHttpHeader.kt, src/test/kotlin/com/whatever/domain/couple/service/CoupleServiceOptimisticLockTest.kt, src/test/kotlin/com/whatever/domain/couple/service/CoupleServiceTest.kt
- close #85 
- couple start date 수정 시 미래의 date를 넣을 수 없도록 변경했습니다.
- couple entity에 status값을 추가했습니다.
- CoupleUserInfoDto에 성별 정보를 추가했습니다.
- Couple.status를 추가했습니다. 
- 해당 상태에 대한 정합성 관리가 필요하다는 단점이 있겠지만, 1. 직관적이고 2. 비즈니스 상태와 멤버의 수는 분리하는 편이 확장성에도 도움이 될 것 같다고 판단했습니다.
=> [Refactor] 커플 Entity 상태식별 컬럼 추가, 수정사항에 따른 couple api 수정

src/main/kotlin/com/whatever/domain/sample/service/SampleService.kt, src/main/resources/application.yaml
- close #95 
- createAccount 메서드에  `@Tx` 적용
- 사용하지 않는 sql-init 제거
- `@Transactional`의 `readOnly` 설정 값은 강제가 아니라는 사실을 몰랐었습니다..!
H2가 사용하는 JdbcConnection의 경우 아래와 같이 setReadOnly값을무시합니다.
따라서 별도의 읽기 전용 옵션으로 H2서버를 실행하지 않는 이상 readOnly Tx에서 write를 진행하도 오류가 나지 않습니다.
그래서 로컬에서 돌려보았을 때 파악하지 못했고, 앞으로 좀 더 주의하겠습니다.
```java
/** 
JdbcConnection.java
**/
/**
* According to the JDBC specs, this setting is only a hint to the database
* to enable optimizations - it does not cause writes to be prohibited.
*
* @param readOnly ignored
* @throws SQLException if the connection is closed
*/
@Override
public void setReadOnly(boolean readOnly) throws SQLException {
try {
if (isDebugEnabled()) {
debugCode("setReadOnly(" + readOnly + ')');
}
checkClosed();
} catch (Exception e) {
throw logAndConvert(e);
}
}
/**
* Returns …
```
=> [Fix] sample signin api Tx문제 해결

src/main/kotlin/com/whatever/domain/user/dto/PutUserProfileRequest.kt, src/main/kotlin/com/whatever/domain/user/service/UserService.kt, src/test/kotlin/com/whatever/domain/user/controller/UserControllerTest.kt
- #88 
- Regex 사용하도록 변경
- 기존 Size, NotBlank 사용하는 편이 좀더 직관적이었던 것 같은데, 따로 방법이 생각나지 않아서 REGEX 사용했습니다.
=> [Fix] Profile Update시, nickname 필드가 Null일 때에도 validation하는 문제 수정

src/main/kotlin/com/whatever/config/SecurityConfig.kt, src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/controller/ScheduleController.kt, src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/controller/dto/CreateScheduleRequest.kt, src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/controller/dto/UpdateScheduleRequest.kt, src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/exception/ScheduleExceptionCode.kt, src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/repository/ScheduleEventRepository.kt, src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/service/ScheduleEventService.kt, src/test/kotlin/com/whatever/domain/calendarevent/scheduleevent/service/ScheduleEventCreateServiceTest.kt, src/test/kotlin/com/whatever/domain/calendarevent/scheduleevent/service/ScheduleEventServiceTest.kt, src/test/kotlin/com/whatever/domain/user/controller/UserControllerTest.kt
- #98 
- 일정 조회 api의 쿼리 수정
- Schedule 생성 api 추가
- 일정 조회에서 잘못된 쿼리를 수정했습니다. 이제 시작일 종료일을 같도록 수정하면, 해당 일자의 일정 조회가 가능합니다.
- 기존 존재하던 Memo Type의 Content에서 Schedule을 생성할 수 있도록 생성 api를 추가했습니다. 
- 한가지 걱정되는 점은 Content -> Schedule일 경우에도 기존의 수정 UI와 동일합니다.
- 따라서 스케줄을 생성하며 Tag를 포함한 Content의 모든 내용을 수정할 수 있기 때문에 update 메서드를 재활용했습니다.
- 이부분은 따로 디자인 & 프론트와 회의를 해서 `Schedule 생성 시 내용 수정` 여부에 대한 방향을 확실하게 잡아야 할 것 같습니다.
=> [Feat] schedule 생성 api 추가, 일정 조회에서 기간 조회가 가능하도록 수정

src/main/kotlin/com/whatever/config/openfeign/KakaoKapiConfig.kt, src/main/kotlin/com/whatever/config/openfeign/KakaoKauthConfig.kt, src/main/kotlin/com/whatever/config/properties/SpecialDayApiProperties.kt, src/main/kotlin/com/whatever/domain/calendarevent/controller/CalendarController.kt, src/main/kotlin/com/whatever/domain/calendarevent/controller/dto/response/HolidayInfoResponse.kt, src/main/kotlin/com/whatever/domain/calendarevent/specialday/client/SpecialDayApiFeignClient.kt, src/main/kotlin/com/whatever/domain/calendarevent/specialday/client/dto/request/HolidayInfoRequestParams.kt, src/main/kotlin/com/whatever/domain/calendarevent/specialday/client/dto/response/HolidayApiResponse.kt, src/main/kotlin/com/whatever/domain/calendarevent/specialday/model/SpecialDay.kt, src/main/kotlin/com/whatever/domain/calendarevent/specialday/model/SpecialDayType.kt, src/main/kotlin/com/whatever/domain/calendarevent/specialday/repository/SpecialDayRepository.kt, src/main/kotlin/com/whatever/domain/calendarevent/specialday/service/SpecialDayService.kt, src/main/kotlin/com/whatever/global/exception/externalserver/specialday/SpecialDayApiException.kt, src/main/kotlin/com/whatever/global/exception/externalserver/specialday/SpecialDayApiExceptionCode.kt, src/main/resources/application-test.yaml, src/main/resources/application.yaml, src/test/kotlin/com/whatever/domain/calendarevent/specialday/service/SpecialDayServiceTest.kt
- #86 
- 특일 정보 수신을 위한 FeignClient 추가
- 특일 Entity 생성
- 특일 조회 api 생성
- 특일 중 국경일+공휴일 정보만 고려했습니다.
- 아래 조건에 따라 주기적 동기화 & 캐싱이 필요하겠지만, 다른 기능이 우선이라고 판단하여 후순위로 작업해두겠습니다
- 데이터 업데이트는 각 오퍼레이션 별로 연 1회 진행.(1 년치 데이터 일괄 업데이트).
- 특일정보의 경우 6~8월 경 과학기술정보통신부에서 월력요항 정보를 공식적으로 발표한 이후에 차차년도 데이터를 먼저 업데이트.(현재연도 기준 +2년).
- 그 외 기념일, 24 절기, 잡은 11 경 업데이트.
- 추가로 임시공휴일 등 갑작스럽게 발생하는 데이터가 생길 경우 데이터는 바로 업데이트(최대 1 일 이내), 대체공휴일이 추가로 지정되는 경우 대통령령이 공식적으로 시행된 이후에 업데이트.
=> [Feat] 휴일 조회 api 추가

src/main/kotlin/com/whatever/domain/content/tag/controller/TagController.kt
- close #127 
- 태그 조회 api swagger auth 버튼 제거
=> [Chore] 태그 조회 api swagger auth 버튼 제거

src/main/kotlin/com/whatever/global/exception/dto/CaramelApiResponse.kt
- close #154 
- JsonSerializer를 정의하여 data 필드가 null일 경우 `{}`가 응답으로 나가도록 변경했습니다.
=> [Refactor] ResponseDto data 필드를 직렬화 시 빈 Json Object가 나가도록 수정

src/main/kotlin/com/whatever/config/SecurityConfig.kt
- close #179 
- metric 수집용 api의 접근 권한을 모두 허용 (reverse proxy에서 차단)
=> [Fix] metric 수집 api permit all

build.gradle, src/main/kotlin/com/whatever/domain/user/service/UserService.kt, src/test/kotlin/com/whatever/domain/user/service/UserServiceTest.kt, src/test/kotlin/com/whatever/domain/user/service/UserServiceUnitTest.kt
- 없음
- updateUserSetting 테스트 코드 추가
- jacoco 추가한 김에 updateUserSetting 쪽 테스트 코드를 추가해봤습니다
- 이전 테스트랑 겹치지 않게 파일 분리했습니다
- 테스트용 함수 internal로 변경해서 외부에서 못쓰게 바꿨습니당
- 준용님 pr 머지 되어야지 UserControllerTest 성공합니다
- getCurrentUserId() 쪽을 잘 몰라서 따라했습니다ㅠ 
- 테스트코드 수정 할 부분 or 추가할 테스트가 있으면 알려주세요 !
- mockito는 처음써봐서 ㅠ 틀린게 있으면 알려주세요
- 이 테스트 에서는 getCurrentUserId() 를 넣어주고 말고의 여부만 테스트 했습니다
( 그 이상의 에러 테스트는 여기 테스트 코드의 책임이 아닌 것 가타서요 ,,!!)
before
after
=> [Feat] update user setting 유닛 테스트 추가

caramel-domain/src/main/kotlin/com/whatever/caramel/domain/balancegame/service/BalanceGameService.kt, caramel-domain/src/test/kotlin/com/whatever/caramel/domain/balancegame/service/BalanceGameServiceTest.kt
- close #223
- balance game test code 추가 했어요 ! 
- 주석 따라서 필요 없다해서 지운 함수가 있어요 !
- 오타 수정했슴다
Couple 내부에 member는 non-null type의 set으로 되어있는데요,
```
protected val mutableMembers: MutableSet<com.whatever.caramel.domain.user.model.User> = mutableSetOf()
val members: Set<com.whatever.caramel.domain.user.model.User> get() = mutableMembers.toSet()
```
getCoupleMemberChoices 에서 아래와 같이 non-nullable 한 members를 findByIdWithMembers 때문에 같이 nullable하게 쓰고 있더라구요
```
...
val couple = coupleRepository.findByIdWithMembers(coupleId)?.members?.map { it.id } ?: return emptyList()
...
```
그래서 아래와 같이 2부분으로 나누어서 더 명확하게 사용했어요
```
val couple = coupleRepository.findByIdWithMembers(coupleId) ?: return emptyList()
val memberIds = couple.members.map { it.id }.ifEmpty { return emptyList() }
```
커버리지 측정하다보니 이게 맞는 것 같아서요 ... …
=> [Test] balance game 테스트 코드 추가

caramel-api/src/main/kotlin/com/whatever/caramel/api/content/controller/dto/response/ContentInfoResponse.kt
- close  #231
- https://whatever-xhr4427.slack.com/archives/C082BGJP546/p1753466387466629 
- TagTto 같아서 수정했습니당
- 맞나요~?
=> [Bug] ContentInfoResponse 에서 tagList 응답 잘못 내려가는 것 수정

caramel-api/src/main/kotlin/com/whatever/caramel/api/calendarevent/scheduleevent/controller/ScheduleController.kt
- close #233 
- https://whatever-xhr4427.slack.com/archives/C082BGJP546/p1753468042528169
- 이전 응답 형식으로 롤백하였습니다.
- 바뀐 형식으로 배포하게 되면 프로덕션 앱이랑 싱크가 안맞습니다.
=> [Fix] /v1/calendar/schedules 에서 응답 모듈화 전으로 롤백
