- .github/ISSUE_TEMPLATE/build.md
- .github/ISSUE_TEMPLATE/discussion.md
- .github/ISSUE_TEMPLATE/docs.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/fix.md
- .github/ISSUE_TEMPLATE/hot-fix.md
- .github/ISSUE_TEMPLATE/refactoring.md
- closed #5 
- 이슈 템플릿 7종 생성
- 추가/삭제할 게 있는지 봐주십쇼
> [Docs] Issue template 정의

- build.gradle
- src/main/kotlin/com/whatever/config/SwaggerConfig.kt
- src/main/kotlin/com/whatever/domain/sample/controller/SampleController.kt
- src/main/resources/application.yaml
- closed #9 
- swagger 의존성 추가 & build.gradel dependencies 정리
- application.yaml에 swagger 기본 세팅 추가
- SwaggerConfig 생성 & jwt 인증인가를 위한 SecurityScheme 추가
- SampleController에 Swagger 예제 추가
> [Feat] Swagger 추가

- src/main/kotlin/com/whatever/global/exception/GlobalControllerAdvice.kt
- src/main/kotlin/com/whatever/global/exception/common/CaramelControllerAdvice.kt
- src/main/kotlin/com/whatever/global/exception/dto/CaramelApiResponse.kt
- src/main/kotlin/com/whatever/global/exception/dto/ErrorResponse.kt
-  #12 
- ApiResponse class 구현
- ExceptionResponse 관련 네이밍 변경 논의
- ExceptionResponse부분이 사실상 클라이언트에 보여지는 부분이여서, Exception이라는 프로그래밍 관점에서의 오류 보다는 Error라는 네이밍이 더 낫지 않을까 하여 제안해봅니다!
> [Feat] ApiResponse 클래스 추가, ExceptionResponse renaming 논의

- build.gradle
- src/main/kotlin/com/whatever/config/properties/JwtProperties.kt
- src/main/kotlin/com/whatever/domain/auth/client/KakaoFeignClient.kt
- src/main/kotlin/com/whatever/domain/auth/client/dto/KakaoIdTokenDto.kt
- src/main/kotlin/com/whatever/domain/auth/client/dto/KakaoOIDCPublicKeysDto.kt
- src/main/kotlin/com/whatever/domain/auth/service/JwtHelper.kt
- src/main/kotlin/com/whatever/domain/auth/service/OIDCHelper.kt
- src/main/kotlin/com/whatever/domain/sample/controller/SampleController.kt
- src/main/kotlin/com/whatever/global/jwt/JwtProvider.kt
- src/main/kotlin/com/whatever/util/DateTimeUtil.kt
- src/main/resources/application-test.yaml
- src/main/resources/application.yaml
- src/test/kotlin/com/whatever/global/jwt/JwtProviderTest.kt
- src/test/kotlin/com/whatever/util/DateTimeUtilTest.kt
- close #15 
- jwt 편의성을 위한 jjwt 의존성 추가
- 시간에 Zone을 명시 & 편의성을 위한 DateTimeUtil 추가
- JwtProvider 추가
- JwtHelper 추가
- OIDCHelper 추가
- JwtProvider는 순수 jwt에 관련된 부분만 남기고, 개발을 하며 사용될 부분은 각 Helper로 분리해보려고 했습니다!
- 또, 캘린더 등 TimeZone을 기준으로 시간을 생성 & 변환해야할 일이 자주 있을것 같아 DateTimeUtil을 만들어봤습니다.
- 토요일 시험이 있어 각 Helper의 테스트코드, CustomException으로 전환을 못했습니다 ㅜㅜ 해당 PR이 반영되면 다른 이슈를 생성해서 나머지 작업을 진행하고, 반영이 안된다면 해당 PR에 이어서 작업하겠습니다.
> [Feat] Jwt Provider 추가

- src/main/resources/application-test.yaml
- src/main/resources/application.yaml
- src/main/resources/console-appender.xml
- src/main/resources/file-appender-error.xml
- src/main/resources/file-appender-info.xml
- src/main/resources/logback-spring.xml
- close #25 
- 기존 application.yaml에 있던 로깅 관련 설정을 제외, logback 파일로 통합시켰습니다.
- ⚠️ 대신, 로그 저장 위치가 들어가는 환경변수가 하나 추가되었습니다.⚠️ 
- 로그 설정을 세부적으로, 앞으로 dev&production 배포 시 로그 저장을 목적으로 logback을 추가했습니다.
- test, local-mem, dev, production 총 4개의 profile을 기준으로 로그 출력 대상과 로그 Level을 분리했습니다.
- 시간 괜찮으시면 허들이나 채팅으로 로그 Level을 어떻게 나눌건지, 어떻게 추가하는지 말씀드리겠습니다!
> [Feat] logback 설정 추가

- Dockerfile
- src/main/resources/application.yaml
- src/test/kotlin/com/whatever/domain/calendarevent/eventrecurrence/model/converter/RecurrenceDaySetConverterTest.kt
- #31 
- 빌드용 Dockerfile 추가
- dev profile용 application.yaml 수정
- test code 실패로 인해 빌드 실패하는 문제 해결
- 익숙한 jenkins로 진행하려고합니다
> [Chore] 개발 서버 배포

- src/main/resources/application.yaml
- close #32 
- application.yaml ddl auto 옵션 수정
> [Fix] dev 이상의 ddl auto 수정

- src/main/kotlin/com/whatever/domain/content/model/Content.kt
- src/main/kotlin/com/whatever/domain/content/model/ContentStatus.kt
- src/main/kotlin/com/whatever/domain/content/model/ContentType.kt
- close #36 
- field 변경
- content type에 맞는 enum 추가
> [Refactor] Content Entity의 status field를 type으로 변경

- src/main/kotlin/com/whatever/domain/auth/dto/SignInResponse.kt
- src/main/kotlin/com/whatever/domain/auth/service/AuthService.kt
- src/main/kotlin/com/whatever/domain/user/service/UserService.kt
- #35 
- coupleid및 userService 관련 리뷰 누락된 부분 반영
> [Fix] signin 관련 리뷰 누락된 부분 수정

- src/main/kotlin/com/whatever/config/SecurityConfig.kt
- src/main/kotlin/com/whatever/domain/auth/controller/AuthController.kt
- src/main/kotlin/com/whatever/domain/sample/controller/SampleController.kt
- src/main/kotlin/com/whatever/domain/sample/service/SampleService.kt
- src/main/kotlin/com/whatever/domain/user/model/User.kt
- src/main/kotlin/com/whatever/domain/user/model/UserGender.kt
- src/main/resources/application.yaml
- src/main/resources/initial-data-local.sql
- close #48 
- swagger가 production or dev 환경일 시 basic auth를 사용한 인증 추가
- 로컬 환경에서의 데이터베이스 test user 추가(MALE, FEMALE)
> [Feat] Swagger 배포버전 로그인 추가, 로컬 환경의 테스트 유저 데이터 추가

- src/test/kotlin/com/whatever/domain/auth/service/provider/KakaoUserProviderTest.kt
- close #50 
- oidc를 사용하는 findOrCreateUser()에 맞추어 테스트 수정
-
> [Fix] UserProviderTest가 oidc를 사용하도록 수정

- build.gradle
- src/main/kotlin/com/whatever/config/SecurityConfig.kt
- src/main/kotlin/com/whatever/domain/couple/controller/CoupleController.kt
- src/main/kotlin/com/whatever/domain/couple/controller/dto/response/CoupleInfoResponse.kt
- src/main/kotlin/com/whatever/domain/couple/controller/dto/response/CoupleInvitationCodeResponse.kt
- src/main/kotlin/com/whatever/domain/couple/exception/CoupleException.kt
- src/main/kotlin/com/whatever/domain/couple/exception/CoupleExceptionCode.kt
- src/main/kotlin/com/whatever/domain/couple/model/Couple.kt
- src/main/kotlin/com/whatever/domain/couple/service/CoupleService.kt
- src/main/kotlin/com/whatever/domain/user/model/User.kt
- src/main/kotlin/com/whatever/global/security/principal/CaramelUserDetails.kt
- src/main/kotlin/com/whatever/global/security/util/SecurityUtil.kt
- src/main/kotlin/com/whatever/util/RedisUtil.kt
- src/test/kotlin/com/whatever/domain/couple/service/CoupleServiceTest.kt
- src/test/kotlin/com/whatever/util/RedisUtilTest.kt
- close #52 
- 커플 코드 생성, 연결 api 추가
- 수술까지 시간 부족으로 테스트코드를 못짰습니다 ㅠㅜ
- 이부분 유의해서 리뷰 부탁드리겠습니다.
- 변경된 파일이 많습니다. 최대한 커밋을 쪼개두었으니 커밋 참고해주시면 감사하겠습니다.
- security의 role hierarchy는 user status와 맞지 않는것 같아 제거했습니다~
> [Feat] 커플 초대 & 연결 API

- src/main/kotlin/com/whatever/domain/sample/controller/SampleController.kt
- src/main/kotlin/com/whatever/domain/sample/service/SampleService.kt
- close #62 
- access token ttl 조절 추가
> [Refactor] Test Accesstoken api

- src/main/kotlin/com/whatever/domain/auth/controller/AuthController.kt
- src/main/kotlin/com/whatever/domain/auth/exception/AuthExceptionCode.kt
- src/main/kotlin/com/whatever/domain/auth/service/AuthService.kt
- src/main/kotlin/com/whatever/domain/auth/service/JwtHelper.kt
- src/main/kotlin/com/whatever/global/jwt/JwtProvider.kt
- src/test/kotlin/com/whatever/domain/auth/service/AuthServiceTest.kt
- #59 
- Refresh API
- TestCode
> [Feat] Refresh API 구현

- src/main/kotlin/com/whatever/domain/couple/exception/CoupleExceptionCode.kt
- src/main/kotlin/com/whatever/domain/couple/exception/CoupleIllegalStateException.kt
- src/main/kotlin/com/whatever/domain/couple/model/Couple.kt
- src/main/kotlin/com/whatever/domain/user/exception/UserExceptionCode.kt
- src/main/kotlin/com/whatever/domain/user/exception/UserIllegalStateException.kt
- src/main/kotlin/com/whatever/domain/user/model/User.kt
- src/main/kotlin/com/whatever/global/exception/GlobalControllerAdvice.kt
- src/main/kotlin/com/whatever/global/exception/GlobalExceptionCode.kt
- close #52 
- custom exception 추가
- global exception handling 추가
> [Refactor] Custom Exception, exception handling 추가

- build.gradle
- src/main/kotlin/com/whatever/WhateverBackendApplication.kt
- src/main/kotlin/com/whatever/config/ApplicationConfig.kt
- src/main/kotlin/com/whatever/domain/couple/controller/CoupleController.kt
- src/main/kotlin/com/whatever/domain/couple/controller/dto/response/CoupleInfoResponse.kt
- src/main/kotlin/com/whatever/domain/couple/exception/CoupleAccessDeniedException.kt
- src/main/kotlin/com/whatever/domain/couple/exception/CoupleExceptionCode.kt
- src/main/kotlin/com/whatever/domain/couple/exception/CoupleIllegalStateException.kt
- src/main/kotlin/com/whatever/domain/couple/model/Couple.kt
- src/main/kotlin/com/whatever/domain/couple/service/CoupleService.kt
- src/main/kotlin/com/whatever/domain/user/repository/UserRepository.kt
- src/main/resources/logback-spring.xml
- src/test/kotlin/com/whatever/domain/couple/service/CoupleServiceOptimisticLockTest.kt
- src/test/kotlin/com/whatever/domain/couple/service/CoupleServiceTest.kt
- close #66 
- couple update api
- couple delete api(보류)
- delete api는 좀 더 이야기를 나누어봐야 할것 같아서 보류합니다!
- update 메서드의 재시도 초과를 테스트하는 CoupleServiceOptimisticLockTest.updateStartDate_WithOptimisticLockFail()가 100% 성공한다는 보장이 없어서 마음에 걸리는데 좋은 의견이 있으실까요? 아니면 굳이 테스트를 작성하지 않아도 괜찮을지 의견이 궁금합니다.
> [Feat] 커플 RUD API 구현

- build.gradle
- src/main/resources/application.yaml
- src/main/resources/console-appender.xml
- src/main/resources/file-appender-error.xml
- src/main/resources/file-appender-info.xml
- src/main/resources/logback-spring.xml
- #72 
- 로그 trace를 위한 opentelemetry 추가
- logback 포맷에 trace id 반영
> [Feat] 모니터링 추가

- src/main/kotlin/com/whatever/domain/user/dto/PostUserProfileRequest.kt
- src/main/kotlin/com/whatever/domain/user/service/UserService.kt
- src/test/kotlin/com/whatever/domain/user/controller/UserControllerTest.kt
- #74 
- 간단하게 gender 입력 받도록 하였습니다.
> [Feat] 유저 생성에 성별 추가

- src/main/resources/application.yaml
- close #76
- 모니터링을 위한 metrics histogram 옵션 추가
> [Fix] 히스토그램 메트릭 옵션 추가

- src/main/kotlin/com/whatever/domain/calendarevent/eventrecurrence/model/EventRecurrence.kt
- src/main/kotlin/com/whatever/domain/calendarevent/eventrecurrence/model/converter/RecurrenceDaySetConverter.kt
- src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/model/ScheduleEvent.kt
- src/main/kotlin/com/whatever/domain/content/model/Content.kt
- src/main/kotlin/com/whatever/domain/content/service/ContentService.kt
- src/main/kotlin/com/whatever/domain/content/service/MemoCreator.kt
- src/main/kotlin/com/whatever/domain/content/service/ScheduleCreator.kt
- src/main/kotlin/com/whatever/util/DateTimeUtil.kt
- #70 
- Schedule Create
- EventReccurence null 처리 하였고 Set Converter null로 처리
- 스케쥴 이벤트 부분 잘 만들어졌을지 봐주십쇼
> [Feat] Schedule Create 구현

- src/main/kotlin/com/whatever/domain/sample/controller/SampleController.kt
- src/main/kotlin/com/whatever/domain/sample/repository/SampleUserRepository.kt
- src/main/kotlin/com/whatever/domain/sample/service/SampleService.kt
- src/main/kotlin/com/whatever/domain/user/model/LoginPlatform.kt
- close #93 
- 개발용 회원가입 추가
- 개발용 로그인 추가
- DB 초기화 트리거는 Jenkins Pipeline으로 생성해겠습니다
> [Feat] 개발용 유저 회원가입 & 로그인 api 추가

- src/main/kotlin/com/whatever/config/SwaggerConfig.kt
- src/main/resources/application.yaml
- #104 
- swagger에 표기되는 서버 url 직접 기재
- 환경변수 업데이트 있으니 확인 부탁드립니다~!
> [Refactor] swagger curl scheme 표기 오류 수정

- src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/exception/ScheduleExceptionCode.kt
- src/main/kotlin/com/whatever/domain/couple/exception/CoupleExceptionCode.kt
- src/main/kotlin/com/whatever/domain/couple/service/CoupleService.kt
- src/main/kotlin/com/whatever/global/exception/GlobalControllerAdvice.kt
- src/main/kotlin/com/whatever/global/exception/GlobalExceptionCode.kt
- src/main/kotlin/com/whatever/global/exception/externalserver/kakao/KakaoServerExceptionCode.kt
- src/main/kotlin/com/whatever/global/jwt/JwtProvider.kt
- src/main/kotlin/com/whatever/global/jwt/exception/JwtExceptionCode.kt
> [Refactor] HttpStatus가 누락된 예외 코드 수정

- build.gradle
- src/main/kotlin/com/whatever/domain/content/controller/ContentController.kt
- src/main/kotlin/com/whatever/domain/content/controller/dto/request/GetContentListQueryParameter.kt
- src/main/kotlin/com/whatever/domain/content/controller/dto/response/ContentInfoResponse.kt
- src/main/kotlin/com/whatever/domain/content/exception/ContentException.kt
- src/main/kotlin/com/whatever/domain/content/exception/ContentExceptionCode.kt
- src/main/kotlin/com/whatever/domain/content/model/Content.kt
- src/main/kotlin/com/whatever/domain/content/repository/ContentRepository.kt
- src/main/kotlin/com/whatever/domain/content/service/ContentService.kt
- src/main/kotlin/com/whatever/global/cursor/Cursor.kt
- src/main/kotlin/com/whatever/global/cursor/CursorRequest.kt
- src/main/kotlin/com/whatever/global/cursor/CursoredResponse.kt
- src/main/kotlin/com/whatever/global/cursor/Sortables.kt
- src/main/kotlin/com/whatever/util/CursorUtil.kt
- src/test/kotlin/com/whatever/domain/content/controller/ContentControllerTest.kt
- src/test/kotlin/com/whatever/domain/content/service/ContentServicePaginationTest.kt
- src/test/kotlin/com/whatever/domain/content/service/ContentServiceTest.kt
- #70 
- 정렬 기준에 따른 페이징 커서 설계
- CursoredResponse, Request 등 공통으로 사용할 수 있는 페이지네이션 클래스 추상화
> [Feat] 컨텐츠(메모) RUD 구현

- src/main/kotlin/com/whatever/domain/couple/controller/dto/response/CoupleInfoResponse.kt
- close #110 
- 클라이언트 요청으로 userStatus 추가
> [Refactor] CoupleUserInfoDto.userStatus 프로퍼티 추가

- src/main/kotlin/com/whatever/domain/calendarevent/controller/CalendarController.kt
- src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/controller/ScheduleController.kt
- src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/controller/dto/GetScheduleResponse.kt
- src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/exception/ScheduleExceptionCode.kt
- src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/service/ScheduleEventService.kt
- src/main/kotlin/com/whatever/domain/content/controller/ContentController.kt
- src/main/kotlin/com/whatever/domain/content/controller/dto/response/ContentInfoResponse.kt
- src/main/kotlin/com/whatever/domain/content/service/ContentService.kt
- src/main/resources/logback-spring.xml
- src/test/kotlin/com/whatever/domain/calendarevent/scheduleevent/service/ScheduleEventServiceTest.kt
- src/test/kotlin/com/whatever/domain/content/service/ContentServiceTest.kt
- close #117 
- id기반 메모 조회 api 추가
- id기반 일정 조회 api 추가
- 일정 목록 조회 엔드포인트(/schedules) 추가
- 클라이언트에서 요청한 api 추가입니다.
> [Feat] id based get api 추가

- src/main/kotlin/com/whatever/domain/auth/service/AuthService.kt
- 토큰 재발행 핫픽스
- 토큰 재발행 시 device id 적용
> [Hotfix] 토큰 재발행 시 device id 추가

- src/main/kotlin/com/whatever/config/SecurityConfig.kt
- 유저 정보 api의 접근 가능 상태를 추가했습니다.
> [Hotfix] get user api 접근 가능 상태 추가

- src/main/kotlin/com/whatever/domain/couple/controller/CoupleController.kt
- src/main/kotlin/com/whatever/domain/couple/controller/dto/response/CoupleAnniversaryResponse.kt
- src/main/kotlin/com/whatever/domain/couple/model/CoupleAnniversaryType.kt
- src/main/kotlin/com/whatever/domain/couple/service/CoupleAnniversaryService.kt
- src/main/kotlin/com/whatever/util/AnniversaryUtil.kt
- src/test/kotlin/com/whatever/domain/couple/service/CoupleAnniversaryServiceTest.kt
- src/test/kotlin/com/whatever/domain/couple/service/CoupleServiceTest.kt
- src/test/kotlin/com/whatever/util/AnniversaryUtilTest.kt
- close #123 
- 기념일 계산 util class 추가
- 기념일 api 추가
- 최대한 일반화를 해봤습니다..!
> [Feat] 커플 기념일 api 추가

- src/main/kotlin/com/whatever/domain/content/tag/controller/TagController.kt
- src/main/kotlin/com/whatever/domain/content/tag/controller/dto/response/TagInfoResponse.kt
- src/main/kotlin/com/whatever/domain/content/tag/repository/TagRepository.kt
- src/main/kotlin/com/whatever/domain/content/tag/service/TagService.kt
- src/main/kotlin/com/whatever/domain/couple/controller/CoupleController.kt
- src/test/kotlin/com/whatever/domain/content/tag/service/TagServiceTest.kt
> [Feat] 태그 조회 api 추가

- src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/repository/ScheduleEventRepository.kt
- src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/service/ScheduleEventService.kt
- src/test/kotlin/com/whatever/domain/calendarevent/scheduleevent/service/ScheduleEventServiceTest.kt
- close #135 
- 정렬 기준에 종료일, id 오름차순 추가
> [Refactor] Schedule 목록 조회 쿼리 수정, Test추가

- src/main/kotlin/com/whatever/config/properties/FirebaseProperties.kt
- src/main/kotlin/com/whatever/domain/firebase/service/FirebaseInitializer.kt
- src/main/kotlin/com/whatever/domain/firebase/service/FirebaseService.kt
- src/main/kotlin/com/whatever/domain/sample/controller/SampleController.kt
- src/main/resources/application.yaml
- close #138 
- 환경변수를 통해 FCM 전송 여부를 결정할 수 있도록 수정
> [Refactor] Fcm 전송 활성화/비활성화 옵션 추가

- src/main/kotlin/com/whatever/domain/balancegame/controller/dto/response/ChooseBalanceGameOptionResponse.kt
- src/main/kotlin/com/whatever/domain/balancegame/controller/dto/response/GetBalanceGameResponse.kt
- src/main/kotlin/com/whatever/domain/balancegame/repository/UserChoiceOptionRepository.kt
- src/main/kotlin/com/whatever/domain/balancegame/service/BalanceGameService.kt
- src/main/resources/application-test.yaml
- src/test/kotlin/com/whatever/domain/balancegame/service/BalanceGameServiceTest.kt
- close #140 
- BalanceGameInfo 수정
- UserChoiceInfo 수정
- getCoupleMemberChoices() 내부 조회 쿼리 수정
> [Refactor] balance game api response 수정

- src/main/kotlin/com/whatever/domain/content/tag/controller/TagController.kt
- src/main/kotlin/com/whatever/domain/content/tag/controller/dto/response/TagInfoResponse.kt
- src/test/kotlin/com/whatever/domain/content/tag/service/TagServiceTest.kt
-  /tags -> /v1/tags
- tag dto 프로퍼티 네이밍 변경
> [Refactor] tag 네이밍 변경

- src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/service/ScheduleEventService.kt
- src/main/kotlin/com/whatever/domain/content/service/ContentService.kt
- src/main/kotlin/com/whatever/domain/content/tag/repository/TagContentMappingRepository.kt
- src/test/kotlin/com/whatever/domain/calendarevent/scheduleevent/service/ScheduleEventServiceTest.kt
- close #144 
- 태그들을 불러오는 과정에서 N+1이 발생해 해결했습니다.
> [Refactor] Content 조회 쿼리 수정

- src/main/kotlin/com/whatever/domain/base/BaseTimeEntity.kt
- src/main/kotlin/com/whatever/domain/content/controller/dto/response/ContentInfoResponse.kt
- src/main/kotlin/com/whatever/domain/firebase/model/FcmToken.kt
- src/main/kotlin/com/whatever/domain/firebase/repository/FcmTokenRepository.kt
- src/main/kotlin/com/whatever/domain/firebase/service/FirebaseService.kt
- src/main/kotlin/com/whatever/domain/sample/repository/SampleUserSettingRepository.kt
- src/main/kotlin/com/whatever/domain/sample/service/SampleService.kt
- src/main/kotlin/com/whatever/domain/user/controller/UserController.kt
- src/main/kotlin/com/whatever/domain/user/dto/PatchUserSettingRequest.kt
- src/main/kotlin/com/whatever/domain/user/dto/PatchUserSettingResponse.kt
- src/main/kotlin/com/whatever/domain/user/dto/UserSettingResponse.kt
- src/main/kotlin/com/whatever/domain/user/exception/UserException.kt
- src/main/kotlin/com/whatever/domain/user/exception/UserExceptionCode.kt
- src/main/kotlin/com/whatever/domain/user/exception/UserIllegalStateException.kt
- src/main/kotlin/com/whatever/domain/user/model/UserSetting.kt
- src/main/kotlin/com/whatever/domain/user/repository/UserSettingRepository.kt
- src/main/kotlin/com/whatever/domain/user/service/UserService.kt
- src/main/resources/application-test.yaml
- src/main/resources/application.yaml
- src/test/kotlin/com/whatever/domain/firebase/service/FirebaseServiceTest.kt
- close #148 
- 유저 설정 테이블이 추가되었습니다.
- 설정 조회 & 조작 api가 추가되었습니다.
- 메모 조회 시 생성일 정보를 추가했습니다.
- db max connection pool을 환경변수로 제어하도록 application.yaml이 수정되었습니다.
> [Feat] 알림 설정 추가, 메모 dto에 생성일 정보 추가

- src/main/kotlin/com/whatever/domain/balancegame/model/BalanceGame.kt
- src/main/kotlin/com/whatever/domain/balancegame/model/UserChoiceOption.kt
- src/main/kotlin/com/whatever/domain/calendarevent/specialday/model/SpecialDay.kt
- src/main/kotlin/com/whatever/domain/content/model/Content.kt
- src/main/kotlin/com/whatever/domain/content/tag/model/TagContentMapping.kt
- src/main/kotlin/com/whatever/domain/firebase/model/FcmToken.kt
- src/main/kotlin/com/whatever/domain/user/model/User.kt
- src/main/resources/application.yaml
- close #156 
- @Table에 인덱스와 unique 제약조건을 명시했습니다.
- dev 환경의 ddl-auto를 validate로 변경했습니다. 앞으로는 ddl을 통해 직접 제약조건을 설정해야합니다.
> [Refactor] DB Entity 제약조건 수정

- src/main/kotlin/com/whatever/domain/calendarevent/scheduleevent/model/ScheduleEvent.kt
- src/main/kotlin/com/whatever/domain/content/exception/ContentExceptionCode.kt
- src/main/kotlin/com/whatever/domain/content/model/Content.kt
- src/main/kotlin/com/whatever/domain/content/model/ContentDetail.kt
- src/main/kotlin/com/whatever/domain/content/tag/model/Tag.kt
- src/main/kotlin/com/whatever/domain/couple/controller/CoupleController.kt
- src/main/kotlin/com/whatever/domain/couple/controller/dto/request/UpdateCoupleRequest.kt
- src/main/kotlin/com/whatever/domain/couple/exception/CoupleExceptionCode.kt
- src/main/kotlin/com/whatever/domain/couple/model/Couple.kt
- src/main/kotlin/com/whatever/domain/user/model/User.kt
- src/main/resources/application.yaml
- src/test/kotlin/com/whatever/domain/content/service/ContentServicePaginationTest.kt
- close #158 
- 개발 당시 미정이었던 컬럼들의 length를 제한했습니다.
- application단에서 체크하기 위해 hibernate validator의 CodePointLength를 사용했습니다.
> [Refactor] update column type

- src/main/kotlin/com/whatever/domain/couple/service/CoupleAnniversaryService.kt
- src/test/kotlin/com/whatever/domain/couple/service/CoupleAnniversaryServiceTest.kt
- close #167 
- 100일 단위 기념일은 최대 300일까지만 조회하도록 수정
> [Refactor] 300일을 초과하는 100일 단위 기념일을 조회하지 않도록 변경

- .gitignore
- 
- 실수로 firebas.json 파일이 올라가지 않도록 합니다
-
> [Chore] gitignore update

- build.gradle
- jacoco 추가
- jacoco 를 추가해봤습니다
- exclude 할 경로, 파일을 같이 고민해봐야해요
> [Feat] jacoco 추가

- build.gradle
- mockk 추가했습니다
- mockk 추가했습니다 [https://mockk.io/]
- mockk 추가했습니다
> [Chore] mockk 추가

- src/test/kotlin/com/whatever/WhateverBackendApplicationTests.kt
- src/test/kotlin/com/whatever/domain/auth/service/provider/KakaoUserProviderTest.kt
- close #57
- 쉬워보여서 제가 했습니다~
- 생각보다 몇개 없네용
> [Refactor] Mockito 사용 테스트코드를 Mockito-Kotlin 스타일로 개선

- Dockerfile
- caramel-api/build.gradle.kts
- caramel-domain/src/main/kotlin/com/whatever/caramel/config/CacheConfig.kt
-close #218
- dockerfile의 jar 파일명과 위치 수정
- log4j는 공통으로 정의되어서 api 모듈의 gradle에서 제거
- cache config는 redis만 사용하므로 confiditional property 제거
> [Refactor] 멀티모듈 빌드 오류 수정

- caramel-api/src/main/kotlin/com/whatever/caramel/api/calendarevent/controller/dto/response/CalendarEventInfoResponse.kt
- caramel-api/src/main/kotlin/com/whatever/caramel/api/calendarevent/scheduleevent/controller/dto/CreateScheduleRequest.kt
- caramel-api/src/main/kotlin/com/whatever/caramel/api/calendarevent/scheduleevent/controller/dto/UpdateScheduleRequest.kt
- caramel-api/src/main/kotlin/com/whatever/caramel/api/content/controller/dto/request/CreateContentRequest.kt
- caramel-api/src/main/kotlin/com/whatever/caramel/api/content/controller/dto/request/UpdateContentRequest.kt
- caramel-api/src/main/kotlin/com/whatever/caramel/api/content/controller/dto/response/ContentInfoResponse.kt
> [Feat] 컨텐츠 담당자 응답 및 요청에 description 변경
